### ISSUE TITLE
Should we use `@spawn` instead of `@async` in some places?

### ISSUE THREAD

**Issue by mchitre** [org-arl/Fjage.jl#18]
Java fjåge uses a thread for each agent, and behaviors are cooperatively multitasked. `Fjage.jl` agents use `@async` for everything -- this means all agents are cooperatively multitasked unless they explicitly spawn their own threads. Change this behavior?

**Comment by mchitre** [comment]
Furthermore, we should probably use a lock around behavior actions to gain the same benefit of cooperative multitasking that we get with the Java/Groovy agents -- no explicit synchronization needed due to the atomic nature of behavior actions.

**Comment by notthetup** [comment]
Another point to note, Julia's logging macros (`@info` etc) seem to `yield` internally, which also makes the any behaviour action non-atomic if they're logging. This can easily cause heisenbugs.

**Comment by mchitre** [comment]
After discussion: agreed to keep `@info` etc to be as they are in Julia (i.e. yielding). Only behaviors of a single agent will be cooperative multitasked.

P.S. We may have special non-yielding versions of log statements for specialized tight loop debugging, if needed.

**Comment by mchitre** [comment]
Implemented
