### ISSUE TITLE
Error in decoding a message with nested numeric arrays in the base64 compressed representation 

### ISSUE THREAD

**Issue by notthetup** [org-arl/Fjage.jl#21]
As defined in the [Gateway spec](https://github.com/org-arl/fjage/blob/dev/gateways/Gateways.md#json-protocol) a Fjåge Gateway (and also the Container) should support decoding of numeric arrays in the base64 compressed representation even if the arrays are nested inside the JSON structure.

It seems that the current implementation only decodes numeric arrays in the base64 compressed representation at the top level of the JSON.

## How to reproduce

- Create a local TCP server using `nc` : `> nc -l 5081`
- In another terminal, run Julia `> julia`
- Add the Fjage.jl package `import Pkg; Pkg.add("Fjage"); using Fjage`
- Create a Fjage gateway in Julia `gw = Gateway("127.0.0.1", 5081)`
- Subscribe to `org.arl.unet.Topics.PARAMCHANGE` : `subscribe(gw, AgentID("org.arl.unet.Topics.PARAMCHANGE", true))`
- Send this JSON String from the TCP server (paste in the terminal where `nc` is running) : `{"action":"send","message":{"clazz":"org.arl.unet.ParamChangeNtf","data":{"paramValues":{"org.arl.unet.nodeinfo.NodeInfoParam.location":{"clazz":"[D","data":"AAAAAAAA8D8AAAAAAAAAQDMzMzMzMwtA"}},"index":-1,"msgID":"7e117014-cab1-48ed-b487-0fbbf1bf6df4","perf":"INFORM","recipient":"#org.arl.unet.Topics.PARAMCHANGE","sender":"node","inReplyTo":null,"sentAt":1673424888970}},"relay":false}`
- Receive a message from the gateway `rsp = receive(gw, 10000)`
- Look at the value of `rsp.paramValues`.

If correctly decoded, the value of `rsp.paramValues` should be a `Dict` with a key "org.arl.unet.nodeinfo.NodeInfoParam.location" and the value of `[1.0, 2.0, 3.4]`.

**Comment by mchitre** [comment]
Fixed by @ettersi with PR #22
