### ISSUE TITLE
Adding agents to non-running containers triggers "Connection lost..."

### ISSUE THREAD

**Issue by ettersi** [org-arl/Fjage.jl#29]
https://github.com/org-arl/Fjage.jl/blob/b109126034cbdc517d8003e783df890677657002/src/container.jl#L385

This line tries to send a message to the master container without checking whether the slave container has started, leading to a somewhat confusing "Connection lost..." warning if you follow the recommended procedure for adding a remote agent:

```julia
c = SlaveContainer(...)
add(c, MyAgent())
start(c)
```

I believe the fix is to change the above line to

```julia
  c isa SlaveContainer && isrunning(c) && _update_watch(c)
```

and add a call to `_update_watch()` to `start(::SlaveContainer)`, but I'll have to properly think this through at some point.

**Comment by mchitre** [comment]
I've assigned this to myself so it doesn't slip through the cracks, but @ettersi, if you end up exploring a solution, I'll be happy to reassign it to you.
