### ISSUE TITLE
Filtering receive can deadlock

### ISSUE THREAD

**Issue by ettersi** [org-arl/Fjage.jl#30]
In this case, code says it better than words...

```julia
#= Run the following before you run this:

curl -O https://raw.githubusercontent.com/org-arl/fjage/master/src/sphinx/fjage_quickstart.sh
sh fjage_quickstart.sh
./fjage.sh

=#

# Overview
#  - Add agent and open a gateway
#  - Agent sends many messages, then gateway receives one of them
#  - When done "right", the gateway will lock forever

using Fjage

# Events to synchronise between agent and gateway
gateway_ready = Threads.Event()
cache_filled = Threads.Event()
receiving = Threads.Event()
sent = Threads.Event()

@agent struct Producer; end
function Fjage.startup(a::Producer)
    # Wait for gateway
    wait(gateway_ready)

    # Fill the gateway's queue of pending messages
    msgno = 0
    for _ = 1:255
        send(a, GenericMessage(; recipient = topic("T"), msgno = msgno+=1))
    end
    request(a, GenericMessage(; recipient = topic("T"), msgno = msgno+=1))
    notify(cache_filled)

    # Wait for gateway to have cached one message ...
    wait(receiving)

    # ... then send two more messages to overflow the gateway's queue
    send(a, GenericMessage(recipient = topic("T"), msgno = msgno+=1))
    request(a, GenericMessage(recipient = topic("T"), msgno = msgno+=1))
    notify(sent)
end

# Start container and Producer
c = SlaveContainer("localhost", 5081, reconnect=false)
add(c, "producer", Producer())
while true
    try
        start(c)
        break
    catch
        sleep(0.1)
    end
end

# Connect gateway
gw = Gateway("localhost", 5081, reconnect=false)
subscribe(gw, topic("T"))
notify(gateway_ready)

# Wait for queue to be filled ...
wait(cache_filled)

# ... then filter out any but the first message
receive(
    gw,
    msg->begin
        if msg.msgno == 2
            notify(receiving)
            wait(sent)
            println("Got the message I want, so now I can carry on, right?")
            return true
        end
        return false
    end
)
println("No you can't, because you'll never get here")
```

This is blocking for me, so I hope I can fix this myself in a reasonable amount of time.

**Comment by mchitre** [comment]
Mixing thread based sync and behaviors often leads to deadlocks. I usually find a behavior based agents much easier to reason about, once you get used to the idea. Can't what you need done be done as behaviors fully?

**Comment by mchitre** [comment]
I am not sure I understand what the requirement here is. You are effectively coupling two agents in two containers through synchronization constructs. Agents aren't meant to be used like that, as the idea of agents is to be event triggered and cooperative. Behaviors don't like to have blocking synchronization calls in them. Perhaps there's a better way to achieve what your need is?

**Comment by ettersi** [comment]
The bug here is a race condition. The synchronisation (the `Threads.Event` variables) is only required to reliably trigger the race condition.

**Comment by mchitre** [comment]
OK.

So `Got the message I want, so now I can carry on, right?` gets printed and `No you can't, because you'll never get here` doesn't?

**Comment by ettersi** [comment]
Correct

**Comment by ettersi** [comment]
The problem is these lines in `receive(gateway, filter, timeout)`: 

https://github.com/org-arl/Fjage.jl/blob/b109126034cbdc517d8003e783df890677657002/src/gw.jl#L350-L352

It is assumed here that the entire cache can fit into the `queue`, but that need not be true if new messages have come in while we were filtering the queue.

**Comment by mchitre** [comment]
We can drop oldest message if we detect this, presumably.

**Comment by mchitre** [comment]
Ah, yes. I have faced this before. Might need a very short term lock around all the pushes to the queue :(

**Comment by ettersi** [comment]
Yes, at which point we might as well get rid of the `Channel` and use a lock-protected `Vector` instead...

**Comment by ettersi** [comment]
Actually, not quite. A `Channel` still gives us the possibility to wait for events...
